### ISSUE TITLE
question: device serial number

### ISSUE THREAD

**Issue by o-lukas** [SmartThingsCommunity/smartthings-core-sdk#195]
**What is your question? Please describe.**
Is there a call to get the serial number of a device?

**Additional context**
I want to get the serial number of my TV using the SmartThings API. I could not find it using one of the API calls. Is there one that I might have missed or is getting the serial number not supported?

**Comment by Sitlintac** [comment]
Unfortunately, device serial numbers are not available through the SmartThings API.
