### ISSUE TITLE
Getting 401 Authorization Required error for BearerTokenAuthenticator

### ISSUE THREAD

**Issue by sit1cob** [SmartThingsCommunity/smartthings-core-sdk#211]
const authenticator = new BearerTokenAuthenticator({
  token: 'xxxxxxx',
});

const client = new SmartThingsClient(authenticator);
client.locations.list().then(locations => {
  console.log(`FoundFoundFound ${locations.length} locations`)
})  .catch(err => {  console.log('errerrerr',err);
  
});

I am getting 401 Authorization Required for a proper PAT

**Comment by rossiam** [comment]
The constructor for `BearerTokenAuthenticator` needs the token to be passed as a simple string:

```
const authenticator = new BearerTokenAuthenticator('xxxxxxx');
```
