### ISSUE TITLE
Add "ordered" Parameter to Devices executeCommand()

### ISSUE THREAD

**Issue by shaivadnai** [SmartThingsCommunity/smartthings-core-sdk#217]
**Is your feature request related to a problem? Please describe.**
While writing a custom script to trigger functionality in my Samsung Fridge, I noticed that this SDK did not support the REST API's [ordered ](https://developer.smartthings.com/docs/api/public/#operation/executeDeviceCommands ) parameter in the SDK

**Describe the solution you'd like**
Add an optional ordered parameter that adds an ordered parameter to the executeCommands payload when ordered === true

**Describe alternatives you've considered**
None at this time - you could technically add another method to the SDK, but the suggested implementation is simpler and wouldn't break the existing API

**Additional context**
![image](https://github.com/SmartThingsCommunity/smartthings-core-sdk/assets/42833164/8d81fc5a-5fb7-4f77-a96b-c1c7b5621f75)

**Comment by shaivadnai** [comment]
I've already implemented this in my own project and can push a branch containing the simple changes specified above (with accompanying tests)

**Comment by rossiam** [comment]
It turns out this parameter is no longer useful. The documentation for it has been updated.
