### ISSUE TITLE
Schlage Connect Zigbee Lock (BE468 ) Event Data Empty

### ISSUE THREAD

**Issue by dinana** [SmartThingsCommunity/smartthings-core-sdk#220]
**Describe the bug**
Event Data is empty

**To Reproduce**
Subscribe to events form the schalge device and the data object in the event will always be empty despite the CLI's edge:drivers:logcat command showing the data object for the event from the driver has a value:
(Home Schlage Door Lock)> emitting event: {"component_id":"main","capability_id":"lock","attribute_id":"lock","state":{"value":"locked","data":{"method":"command"}}}
and here's the event from the SDK:
{"eventTime":"2023-09-14T11:17:51Z","eventType":"DEVICE_EVENT","deviceEvent":{"eventId":"*","locationId":"*","ownerId":"*","ownerType":"LOCATION","deviceId":"*","componentId":"main","capability":"lock","attribute":"lock","value":"unlocked","valueType":"string","stateChange":true,"data":{},"subscriptionName":"*"}}

**Expected behavior**
the data object should be populated as captured by the edge driver

**Actual behavior**
the data object is empty

**Comment by nayelyzarazua-bluetrail** [comment]
Hi, @dinana 
Please send us an email at build@smartthings.com with the description of this issue and we'll continue the support there.
