### ISSUE TITLE
no health event is coming

### ISSUE THREAD

**Issue by jeesunhub** [SmartThingsCommunity/smartthings-core-sdk#45]
called subscribeToDeviceHealth() function.
when device goes to offline or online, DEVICE_HEALTH_EVENT is supposed to be come.
but it is not.

scope":["r:locations:*","x:devices:*","r:devices:*"] are used.

but subscribeToDeviceLifecycle() is well working, when device is registered and unregistered with DEVICE_LIFECYCLE_EVENT.

**Comment by bflorian** [comment]
We've verified that the problem here is that the platform is not sending an event, so no fix to the SDK is required. We'll keep this issue open until the platform fix is deployed.

**Comment by bflorian** [comment]
The platform fix has been deployed and device health events are once again working
