### ISSUE TITLE
typo in WIKI

### ISSUE THREAD

**Issue by jeesunhub** [SmartThingsCommunity/smartthings-core-sdk#50]
https://github.com/SmartThingsCommunity/smartthings-core-sdk/wiki/Devices#deprecated-functions

> getCapabilityState - Gets the attribute values of the specified component capability. Deprecated use getCapabilityState() instead.
> getCapabilityState - Gets the attribute values of the specified component capability. Deprecated use getCapabilityStatus() instead.

**Comment by rossiam** [comment]
Wiki updated.
