### ISSUE TITLE
Rules API RuleRequest typing is wrong

### ISSUE THREAD

**Issue by jimmyfortinx** [SmartThingsCommunity/smartthings-core-sdk#56]
I used this project with Typescript to create a new rule and typing is misleading us on the data structure.

- https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/master/src/endpoint/rules.ts#L46
- https://smartthings.developer.samsung.com/docs/api-ref/st-api.html#operation/createRule

For example: `greaterThan` should be `greater_than` and `_else` should be `else`

When I follow the typing I receive this from the server:
```
{"code":"BodyMalformedError","target":"greaterThan","message":"Unknown field on line 1","details":[]}]}
```

If you don't want to use the same name convention on JS side, you should at least process the data to remap them.

**Comment by bflorian** [comment]
@jimmyfortinx this issue was actually a case of the SDK types being changed earlier than the platform change. That platform change has now been deployed and existing rules migrated. Both the API and SDK should be consistent now -- the value should be `greaterThan` not `greater_than`.
