### ISSUE TITLE
create subscription api should be use POST method?!

### ISSUE THREAD

**Issue by brian8520** [SmartThingsCommunity/smartthings-core-sdk#63]
create subscription API method doesn't match. I think It  should be POST, but PUT.

API description : https://librarian-regionals.smartthingsgdev.com/api/api.smartthings.com.v1#operation/saveSubscription 
core-sdk : https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/57b01a6e83d1d9c85561bbe629f3657351251b8c/src/endpoint/subscriptions.ts#L258

error console : 
Error: Request failed with status code 405: {"requestId":"D70F1365-36AE-4990-9BAE-5D3EDCF8E5E7","error":{"code":"MethodNotAllowedError","message":"PUT is not an allowed HTTP method for the requested resource.","details":[]}}

**Comment by bflorian** [comment]
Fix deployed in version 2.4.1
