### ISSUE TITLE
2 Questions using smartthings-core-sdk/src/endpoint/devices apis

### ISSUE THREAD

**Issue by solmar36** [SmartThingsCommunity/smartthings-core-sdk#70]
Is there a way to delete devices within installedAppId?
(delete the devices installed by specific Installedapp)
https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/57b01a6e83d1d9c85561bbe629f3657351251b8c/src/endpoint/devices.ts#L320

Is there a way to create devices with not only locationId but also the roomId?
(If I use the create api, it only generates the device at the location with no room specified)
https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/57b01a6e83d1d9c85561bbe629f3657351251b8c/src/endpoint/devices.ts#L330

**Comment by bflorian** [comment]
@solmar36 these are both good suggestions but not currently supported in the API. We'll create tickets for them and keep this issue open for status updates.

Regarding the deleting of devices installed by a specific installed app, as you might already know, those devices will be deleted by the platform when that installed app is deleted. You don't have to explicitly delete them in the uninstalled handler. But if you want to delete them from the installedapp itself you have to list and delete them individually at this time.

**Comment by solmar36** [comment]
@bflorian The reason why I've tried the deletion with the installedapp was to use inside UPDATE lifecycle. 
When we do updates(use separately with install), sometimes devices might be deleted on the other side, and this is within the specific installed app(because it's in smartapp's update lifecycle). 

Thank you for the comments, and it will be helpful if there are both API with more optional parameters.

**Comment by bflorian** [comment]
@solmar36 that makes sense. To make sure I was clear in my response, your app should be able to delete any devices it created in the UPDATE lifecycle without requiring any scopes beyond `i:deviceprofiles:*`. You just need to make a separate API call for each device.

**Comment by solmar36** [comment]
@bflorian Sorry for the confusion, what I was thinking is whether it's possible to list up devices that is in installedAppId, so that I can compare and update(create and delete)
https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/57b01a6e83d1d9c85561bbe629f3657351251b8c/src/endpoint/devices.ts#L249

**Comment by bflorian** [comment]
@solmar36 it looks like this feature was added to the API but not this SDK. 

To reiterate, if your app has only the `i:deviceprofiles:*` scope then just calling `client.devices.list()` without any arguments will list only the devices you created with that installed app. 

However, if your app also has the `r:devices:*` scope you will then get a list of all devices. We will update the SDK to include an option for filtering by installedAppId.
