### ISSUE TITLE
Typescript Function parameters

### ISSUE THREAD

**Issue by arnldmthd** [SmartThingsCommunity/smartthings-core-sdk#86]
Could you write these input parameters as object as well
![image](https://user-images.githubusercontent.com/29730952/103816325-7afd2580-506d-11eb-8a92-65e5defbf6ee.png)
In this way
![image](https://user-images.githubusercontent.com/29730952/103816674-0bd40100-506e-11eb-9933-775c2a11da6d.png)
I think using objects as input params makes it way more errorless and easier to extend input parameters

**Comment by rossiam** [comment]
The `create` method might be what you're looking for:

https://github.com/SmartThingsCommunity/smartthings-core-sdk/blob/f7c808a1a62cc3ccaa83fd08cda25713546daafb/src/endpoint/subscriptions.ts#L257
