### ISSUE TITLE
client.subscriptions.create() Outdated

### ISSUE THREAD

**Issue by arnldmthd** [SmartThingsCommunity/smartthings-core-sdk#90]
Only required params seems to be sourceType
![image](https://user-images.githubusercontent.com/29730952/103821441-ce27a600-5076-11eb-8c7d-477a518e5aab.png)

However 
![image](https://user-images.githubusercontent.com/29730952/103821495-e7c8ed80-5076-11eb-95ad-21f1a9dd19be.png)

**Comment by bflorian** [comment]
The documentation and error message could be clearer. While `sourceType` is the only parameter that is actually required for all create calls, one of the subscription detail params is also required:
```
export interface SubscriptionRequest {
	sourceType: SubscriptionSource
	device?: DeviceSubscriptionDetail
	capability?: CapabilitySubscriptionDetail
	mode?: ModeSubscriptionDetail
	deviceLifecycle?: DeviceLifecycleDetail
	deviceHealth?: DeviceHealthDetail
	securityArmState?: SecurityArmStateDetail
	hubHealth?: HubHealthDetail
	sceneLifecycle?: SceneLifecycleDetail
}
```
